### ISSUE TITLE
`DeferredText` - support for `String` resolution

### ISSUE THREAD

**Issue by Hariofspades** [Backbase/DeferredResources#20]
`DeferredText` is always resolved to `CharSequence`. It would be nice to add support to resolve to `String` as well.

**Comment by Hariofspades** [comment]
* It can either be a new method - `DeferredText.resolveAsString(context)` or
* It can also be generic type - 'DeferredText.resolve<T>(context)` (this might break I think)

**Comment by drewhamilton** [comment]
Good idea! I don't think making it generic really works, because the implementation needs to know what type to return. CharSequence and String are simple enough, but what should `DeferredText.Resource`'s behavior be if `T` is `Spannable`?

That leaves the `resolveAsString` option. It could be added as an extension function or an interface function. Is there a valid use case where `resolveAsString` should return anything other than `resolve(context).toString()`? If not, extension function is probably preferable because it doesn't complicate the interface. But if there is a valid case, then it should be part of the interface so implementations can change the default behavior.

**Comment by drewhamilton** [comment]
After sitting on this overnight I'm leaning strongly toward the extension function version, because I see this as a convenience around the DeferredText API rather than something inherent to it. Also thinking `resolveToString` rather than `resolveAsString`.

PR coming shortly.
